### ISSUE TITLE
Ratchet and Clank USA SLUS extraction problem

### ISSUE THREAD

**Issue by YAGAMI55** [chaoticgd/wrench#116]
Hi. can i extract iso usa region of the game (Ratchet and Clank 1)?

Ill try... Your tool say what cant this.
![image](https://user-images.githubusercontent.com/62074757/116411633-910e3c00-a83e-11eb-9cfd-526d57eca8f4.png)

**Comment by YAGAMI55** [comment]
Sorry! not SLUS
SCUS_971.99

**Comment by chaoticgd** [comment]
Ratchet & Clank 1 isn't currently supported. I've been planning on adding support for it but I don't have the time to work on it right now.

**Comment by chaoticgd** [comment]
See https://github.com/chaoticgd/wrench/blob/master/docs/compatibility_matrix.md
