### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by benjolos** [chaoticgd/wrench#146]
Hey there,

I followed every step in your readme, but i keep having an Access Denied error on ALL BUILD, so the program won’t launch.

I tried so many things i don’t really know what do to anymore. Files are not in read only, VS was started as an administrator, tho it won’t open.

Could you help me ?
Thanks in advance

**Comment by chaoticgd** [comment]
> VS was started as an administrator

I haven't actually tried building it using the Visual Studio GUI, I'm not sure if that's what you're implying here. I've always used the VS developer command prompt (I only occasionally do this to make sure the it's still working on Windows).

Can you reply with a screenshot of the error, along with information as to what step of the process you are getting this error on?

**Comment by benjolos** [comment]
Sorry for the late reply. I finally managed to open the program but everytime i try opening a file like a level the program crashes. How can i fix this ?

**Comment by benjolos** [comment]
(I tried R&C 2 and Deadlocked so far). No problem with extraction

**Comment by benjolos** [comment]
Tested with Debug config also crashes while clicking on a level in tree

**Comment by chaoticgd** [comment]
Does it crash when opening the menu or when clicking on a file? If it's the latter clicking on a level.json file may be the only thing that works currently. Wrench is still in development and some things won't work currently.

**Comment by chaoticgd** [comment]
Since I've not got a response I'm going to assume that fixed the problem you were having, so I'll close this now.

**Comment by chaoticgd** [comment]
I believe I originally misinterpreted what the problem you were having was. Either way I've since fixed some stuff on Windows so it should work now.
