### ISSUE TITLE
Question about the level editor

### ISSUE THREAD

**Issue by Philip762** [chaoticgd/wrench#222]
Hi

Im not sure if this is the right place to post this, but I dont where else to do this.
I recently discovered wrench and I am interested in the level editor aspect of it.
I managed to extract a game, open it in the editor and move around levels.
My question is: "Is there a way to play a level that has changed?"
For example if I change some things like bolt values of enemies, can I play the game where enemies drop the modified amount?

**Comment by chaoticgd** [comment]
Yes, you can build an new ISO with the modified assets, but currently there are a bunch of caveats to it.

The level editor portion of Wrench it currently extremely basic, the vast majority of the effort that's gone into it so far has been more geared towards reversing the engine and developing the tools to unpack and repack the game's files.

Another problem is currently the repacked versions of the game are quite buggy, the main problem currently being textures glitching out.

I don't remember trying to change bolt values for enemies specifically, although from just having a look at the code it seems plausible to me that it would work for R&C2, R&C3 and Deadlocked but probably not R&C1 currently although I might be mistaken.

**Comment by chaoticgd** [comment]
To build and run a level, you should specify the path of PCSX2 in the settings, make sure your changes are saved (File->Save, also the files must be stored in the folder for your mod), and click the 'Build & Run' button near the top of the editor window. I recommend using the drop down to the left of it to configure the build such as to make it much quicker e.g. only write out a single level and skip writing out MPEG cutscenes.

**Comment by chaoticgd** [comment]
Just tested it with R&C2 and it seems to be working, although the games calculate the amount of bolts you get somewhat dynamically so the amount you get won't be exactly equal to the bolts field, but it should affect it.

**Comment by chaoticgd** [comment]
Any further questions, or can I close this?

**Comment by PhilipNousPXL** [comment]
Yeah sure, you can close it.That were all my questions.Thank you for explaining!
